/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ConfigProvider: typeof import('./src/components/ConfigProvider.vue')['default']
    CusAddress: typeof import('./src/components/CusAddress.vue')['default']
    CusAddressList: typeof import('./src/components/CusAddressList.vue')['default']
    CusCard: typeof import('./src/components/CusCard.vue')['default']
    CusCategory: typeof import('./src/components/CusCategory.vue')['default']
    CusCell: typeof import('./src/components/CusCell.vue')['default']
    CusComment: typeof import('./src/components/CusComment.vue')['default']
    CusComponent: typeof import('./src/components/CusComponent.vue')['default']
    CusEmpty: typeof import('./src/components/CusEmpty.vue')['default']
    CusFixedNav: typeof import('./src/components/CusFixedNav.vue')['default']
    CusImagePreview: typeof import('./src/components/CusImagePreview.vue')['default']
    CusMenu: typeof import('./src/components/CusMenu.vue')['default']
    CusNavbar: typeof import('./src/components/CusNavbar.vue')['default']
    CusNoticebar: typeof import('./src/components/CusNoticebar.vue')['default']
    CusSearchbar: typeof import('./src/components/CusSearchbar.vue')['default']
    CusSku: typeof import('./src/components/CusSku.vue')['default']
    CusSwiper: typeof import('./src/components/CusSwiper.vue')['default']
    CusTabbar: typeof import('./src/components/CusTabbar.vue')['default']
    CusTimeSelect: typeof import('./src/components/CusTimeSelect.vue')['default']
    CusTour: typeof import('./src/components/CusTour.vue')['default']
    CusWatermark: typeof import('./src/components/CusWatermark.vue')['default']
    CusWaterMark: typeof import('./src/components/CusWaterMark.vue')['default']
    NutAddress: typeof import('@nutui/nutui-taro')['Address']
    NutAddressList: typeof import('@nutui/nutui-taro')['AddressList']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutCard: typeof import('@nutui/nutui-taro')['Card']
    NutCategory: typeof import('@nutui/nutui-taro')['Category']
    NutCategoryPane: typeof import('@nutui/nutui-taro')['CategoryPane']
    NutCell: typeof import('@nutui/nutui-taro')['Cell']
    NutComment: typeof import('@nutui/nutui-taro')['Comment']
    NutConfigProvider: typeof import('@nutui/nutui-taro')['ConfigProvider']
    NutEmpty: typeof import('@nutui/nutui-taro')['Empty']
    NutFixedNav: typeof import('@nutui/nutui-taro')['FixedNav']
    NutGrid: typeof import('@nutui/nutui-taro')['Grid']
    NutGridItem: typeof import('@nutui/nutui-taro')['GridItem']
    NutImagePreview: typeof import('@nutui/nutui-taro')['ImagePreview']
    NutList: typeof import('@nutui/nutui-taro')['List']
    NutMenu: typeof import('@nutui/nutui-taro')['Menu']
    NutMenuItem: typeof import('@nutui/nutui-taro')['MenuItem']
    NutNavbar: typeof import('@nutui/nutui-taro')['Navbar']
    NutNoticebar: typeof import('@nutui/nutui-taro')['Noticebar']
    NutSearchbar: typeof import('@nutui/nutui-taro')['Searchbar']
    NutSku: typeof import('@nutui/nutui-taro')['Sku']
    NutSwiper: typeof import('@nutui/nutui-taro')['Swiper']
    NutSwiperItem: typeof import('@nutui/nutui-taro')['SwiperItem']
    NutSwitch: typeof import('@nutui/nutui-taro')['Switch']
    NutTabbar: typeof import('@nutui/nutui-taro')['Tabbar']
    NutTabbarItem: typeof import('@nutui/nutui-taro')['TabbarItem']
    NutTimeDetail: typeof import('@nutui/nutui-taro')['TimeDetail']
    NutTimePannel: typeof import('@nutui/nutui-taro')['TimePannel']
    NutTimeSelect: typeof import('@nutui/nutui-taro')['TimeSelect']
    NutTour: typeof import('@nutui/nutui-taro')['Tour']
    NutWatermark: typeof import('@nutui/nutui-taro')['Watermark']
  }
}
